#!/usr/bin/env bash
set -euo pipefail

# Inputs from environment
RAW_IMAGES="${RAW_IMAGES:?RAW_IMAGES is required}"
GHCR_OWNER_RAW="${GHCR_OWNER_RAW:?GHCR_OWNER_RAW is required}"
REPO_FULL="${REPO_FULL:?REPO_FULL is required}"

OWNER=$(echo "$GHCR_OWNER_RAW" | tr '[:upper:]' '[:lower:]')
TIMESTAMP=$(date -u '+%Y-%m-%d %H:%M UTC')

# Known "Used By" mappings — update when downstream repos change base images
declare -A USED_BY=(
  ["node:current-alpine"]="context7-mcp-docker"
  ["node:current-slim"]=""
  ["node:22-slim"]="gitnexus-docker"
  ["node:22-trixie-slim"]="gitnexus-docker"
  ["node:22-alpine"]=""
  ["node:alpine"]="MCP docker repos (time, fetch, brave, etc.)"
  ["golang:1.26-alpine"]="db-MCP-server-docker"
  ["alpine:latest"]="nfs-server, samba-server, proftpd, db-MCP"
  ["python:3-slim"]="codegraphcontext-mcp-docker"
  ["debian:bookworm-slim"]="ispyagentdvr"
  ["debian:trixie-slim"]="ispyagentdvr, vllm-cpu, gitnexus-docker"
  ["debian:stable-slim"]="ispyagentdvr"
)

# Parse image list
IMAGES=$(echo "$RAW_IMAGES" | tr ',' '\n' | sed 's/^ *//;s/ *$//' | sed '/^$/d' | sort -u)

# Build table rows
TABLE_ROWS=""
while IFS= read -r IMG; do
  [[ -z "$IMG" ]] && continue
  TARGET="ghcr.io/${OWNER}/base-images/${IMG}"

  # Query architectures
  ARCHS=""
  ARCHS=$(docker buildx imagetools inspect "$TARGET" 2>/dev/null \
    | grep -oP 'linux/\S+' | sort -u | paste -sd ', ' -) || true
  [[ -z "$ARCHS" ]] && ARCHS="N/A"

  # Determine status
  if docker buildx imagetools inspect "$TARGET" &>/dev/null; then
    STATUS="Mirrored"
  else
    STATUS="Not found"
  fi

  USED="${USED_BY[$IMG]:-}"
  [[ -z "$USED" ]] && USED="—"

  TABLE_ROWS+="| \`${IMG}\` | \`${TARGET}\` | ${ARCHS} | ${USED} | ${STATUS} |"$'\n'
done <<< "$IMAGES"

# Write README
cat > README.md <<EOF
# Base Images Mirror

[![Mirror Base Images to GHCR](https://github.com/${REPO_FULL}/actions/workflows/mirror-base-images.yml/badge.svg)](https://github.com/${REPO_FULL}/actions/workflows/mirror-base-images.yml)

Centralized Docker base image mirror from Docker Hub to GitHub Container Registry (GHCR).

## Purpose

Avoids Docker Hub pull rate limits by mirroring base images to GHCR, which has unlimited pulls with \`GITHUB_TOKEN\` in GitHub Actions.

## Mirrored Images

> **Last synced:** ${TIMESTAMP}

| Source (Docker Hub) | GHCR Mirror | Architectures | Used By | Status |
|:-------------------|:------------|:--------------|:--------|:-------|
${TABLE_ROWS}
## Adding / Removing Images

1. Go to **Settings > Variables > Actions** in this repo
2. Edit the \`BASE_IMAGES\` variable (comma-separated list)
3. Trigger the workflow — no code changes needed

## Trigger

- **cron-job.org**: POST to \`https://api.github.com/repos/${REPO_FULL}/dispatches\` with body \`{"event_type": "mirror-base-images"}\`
- **Manual**: Actions > Mirror Base Images to GHCR > Run workflow

## Usage in Other Repos

Set \`BASE_IMAGE_DEFAULT\` variable in your repo:

\`\`\`
ghcr.io/${OWNER}/base-images/node:22-slim
\`\`\`

---

*This README is auto-generated by the [mirror workflow](https://github.com/${REPO_FULL}/actions/workflows/mirror-base-images.yml). Do not edit manually.*
EOF

echo "README.md generated successfully"
